### ISSUE TITLE
Files placed in the "Sound Files" folder don't show up

### ISSUE THREAD

**Issue by GrucciNishikino** [alentoghostflame/Python-Linux-Soundboard#1]
It's as simple as that.

**Comment by takov751** [comment]
To make it simple in the code, The creator made it in a way, that you have to put a number front of Directory and audio file.

example :  directory name `1 soundboard` inside there is `1 wow.wav` , `2 omg.wav` etc

**Comment by alentoghostflame** [comment]
Holy crap, why didn't I see this?
I recently did a massive rewrite of this soundboard that fixed this issue!
